### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method...

### ISSUE THREAD

**Issue by iRYO400** [hotchemi/Android-Rate#100]
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference`

MainActivity
```
@Override
onCreate()...
{
...
        //RateApp
        AppRate.with(this)
                .setInstallDays(2) // default 10, 0 means install day.
                .setLaunchTimes(2)
                .setRemindInterval(2) // default 1
                .setShowLaterButton(true) // default true
                .setTitle(R.string.support_me)
                .setMessage(R.string.support_message)
                .setTextLater(R.string.support_later)
                .setTextNever(R.string.support_no)
                .setTextRateNow(R.string.support_now)
                .monitor();
}

@Override
onResume{
...
AppRate.showRateDialogIfMeetsConditions(this);
}
```

Exception's log
```
java.lang.RuntimeException: Unable to resume activity {com.r400.ultra.free.rwallpapers/com.r400.ultra.free.rwallpapers.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3050)
                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3081)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:211)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                                   at hotchemi.android.rate.DialogOptions.getListener(DialogOptions.java:136)
                                                                                   at hotchemi.android.rate.DialogManager.create(DialogManager.java:32)
                                                                                   at hotchemi.android.rate.AppRate.showRateDialog(AppRate.java:190)
                                                                                   at hotchemi.android.rate.AppRate.showRateDialogIfMeetsConditions(AppRate.java:51)
                                                                                   at com.r400.ultra.free.rwallpapers.activity.MainActivity.onResume(MainActivity.java:285)
                                                                                   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
                                                                                   at android.app.Activity.performResume(Activity.java:6076)
                                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3039)
                                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3081) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2447) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:156) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:211) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5389) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
```

Please, help

**Comment by hotchemi** [comment]
I'll fix soon.
