### ISSUE TITLE
Crash reports 

### ISSUE THREAD

**Issue by thinkpozzitive** [hotchemi/Android-Rate#75]
Hi hotchemi,

I've been receiving crash reports related to the AppRate library but for the likes of me I cannot reproduce it, nor can I figure out why it is happening, so I'm pasting below the information I have and maybe you have a recommendation.

All the information I have on the crash log:
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean a.a.a.a.h' on a null object reference
       at hotchemi.android.rate.AppRate.with(Unknown Source)
       at com.app.myapp.myActivity$1$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```
What I'm doing is, after a specific user action, I use a 1 second delay (like below) to then show the rate dialog:
```java
Handler handler = new Handler();
handler.postDelayed(new Runnable() {
	@Override
	public void run() {
	  // Show a dialog if meets conditions
	  AppRate.showRateDialogIfMeetsConditions(myActivity.this);
	}
}, 1000);
```

**Comment by hotchemi** [comment]
1. Could u decrypt the stack trace with mapping.txt? I'd like to see the detail.
2. Could u show me where u initialize the AppRate(with `with`). The stack trace shows `AppRate.with`.
2. Why r u launching the dialog with 1 second delay? I think it may cause the problem.
